spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gvv?serverTimezone=UTC
    username: root
    password: Ab1142243318*
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-wait-millis: 150
      max-total: 100
